name: Build JAR artifact

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: build/libs/extensibility-helper-*.jar
        retention-days: 7